version: "3.8"
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
      - api
    networks:
      - network-backend

  web:
    build: ./frontend
    depends_on:
      - api
    networks:
      - network-backend

  api:
    build: ./backend
    depends_on:
      - mongo
    networks: 
     - network-backend

  mongo:
    image: mongo
    restart: always
    volumes: 
      - mongodb_data:/data/db
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks: 
     - network-backend

networks:
  network-backend:

volumes: 
  mongodb_data:
